[package]
name = "dynser-derive"
version = "0.1.0"
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.12"
syn = "0.15.33"
synstructure = "0.10.1"
proc-macro2 = "0.4.29"